// Renders mined rules as the .claude/rules/cli-corrections.md payload (#43).
using System.Globalization;
using System.Text;
using Vtk.Core.Spool;

namespace Vtk.Core.Learn;

public static class RulesFile
{
    /// <summary>The default rules-file path, relative to the project root.</summary>
    public static readonly string DefaultRelativePath =
        Path.Combine(".claude", "rules", "cli-corrections.md");

    /// <summary>
    /// Deterministic markdown for a rule set (assumed pre-sorted by
    /// RuleMiner). Command text passes through the spool redaction pass so
    /// credentials that appeared on a session command line never land in a
    /// committed rules file.
    /// </summary>
    public static string Render(IReadOnlyList<Rule> rules)
    {
        var sb = new StringBuilder();
        sb.Append("# CLI corrections (generated by `vtk learn`)\n\n");
        sb.Append("Fail→succeed command pairs mined from Claude Code session history.\n");
        sb.Append("Use the corrected form directly; do not repeat the failing one.\n");
        sb.Append("Regenerate with `vtk learn` — do not hand-edit.\n\n");
        if (rules.Count == 0)
        {
            sb.Append("No rules mined.\n");
            return sb.ToString();
        }
        foreach (var r in rules)
        {
            sb.Append("- `").Append(Inline(Store.Redact(r.Wrong)))
              .Append("` → `").Append(Inline(Store.Redact(r.Right)))
              .Append("` — ").Append(ErrorClassifier.Name(r.Error))
              .Append(", seen ").Append(r.Occurrences.ToString(CultureInfo.InvariantCulture))
              .Append("x, confidence ").Append(r.Confidence.ToString("0.00", CultureInfo.InvariantCulture))
              .Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>Flattens a command to a single markdown-code-safe line (newlines and backticks would break the list rendering).</summary>
    private static string Inline(string s) =>
        s.Replace("\r", " ").Replace("\n", " ").Replace("`", "'");
}
