using Vtk.Core.Learn;

namespace Vtk.Tests.Learn;

/// <summary>
/// Golden render of the generated cli-corrections.md (#43), including the
/// credential-redaction pass and markdown flattening of awkward commands.
/// </summary>
public class RulesFileTests
{
    [Fact]
    public void Render_GoldenOutput()
    {
        var rules = new[]
        {
            new Rule("git", "git satus", "git status", ErrorType.CommandNotFound, 2, 0.75),
            new Rule("npm", "npm run lint --ext .ts", "npm run lint -- --ext .ts", ErrorType.UnknownFlag, 1, 0.5),
        };

        var got = RulesFile.Render(rules);

        var want =
            "# CLI corrections (generated by `vtk learn`)\n" +
            "\n" +
            "Fail→succeed command pairs mined from Claude Code session history.\n" +
            "Use the corrected form directly; do not repeat the failing one.\n" +
            "Regenerate with `vtk learn` — do not hand-edit.\n" +
            "\n" +
            "- `git satus` → `git status` — command-not-found, seen 2x, confidence 0.75\n" +
            "- `npm run lint --ext .ts` → `npm run lint -- --ext .ts` — unknown-flag, seen 1x, confidence 0.50\n";
        Assert.Equal(want, got);
    }

    [Fact]
    public void Render_RedactsCredentials()
    {
        var rules = new[]
        {
            new Rule("curl",
                "curl -H \"Authorization: Bearer abc123\" https://x",
                "curl -sf -H \"Authorization: Bearer abc123\" https://x",
                ErrorType.Other, 1, 0.5),
        };

        var got = RulesFile.Render(rules);

        Assert.DoesNotContain("abc123", got);
        Assert.Contains("[REDACTED]", got);
    }

    [Fact]
    public void Render_FlattensNewlinesAndBackticks()
    {
        var rules = new[]
        {
            new Rule("echo", "echo `hi`\necho there", "echo hi there", ErrorType.WrongSyntax, 1, 0.5),
        };

        var got = RulesFile.Render(rules);

        Assert.Contains("- `echo 'hi' echo there` → `echo hi there`", got);
    }

    [Fact]
    public void Render_EmptyRules_SaysSo()
    {
        Assert.Contains("No rules mined.", RulesFile.Render(Array.Empty<Rule>()));
    }
}
